version: '3'

services:
  server:
    image: registry.gitlab.com/commento/commento:v1.8.0
    ports:
      - 8080:8080
    environment:
      COMMENTO_ORIGIN: http://ramadan.eu5.org:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://new_user:newpass@db:5432/commento?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: newpass
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:

volumes:
  postgres_data_volume:
